# Generated by Django 2.1.1 on 2018-10-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='имя автора')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='краткое описание автора')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название продукта')),
                ('url_name', models.CharField(max_length=128, verbose_name='название ссылки продукта')),
                ('image_file', models.ImageField(blank=True, upload_to='books_images')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='краткое описание продукта')),
                ('alt', models.CharField(default='book_cover', max_length=128, verbose_name='значение alt для тега img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Main')),
            ],
        ),
    ]
