# Generated by Django 2.1.1 on 2018-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181021_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
