# Generated by Django 2.1.1 on 2018-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181028_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
