# Generated by Django 2.1.1 on 2018-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20181028_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='url_name',
        ),
    ]
