# Generated by Django 2.1.1 on 2018-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcatalog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='краткое описание продукта'),
        ),
    ]
