<Sprite>
    bgcolor: 1, 1, 1, 1
    size_hint: None, None
    size: [app.sprite_size] * 2
    pos: [x * app.sprite_size for x in self.coord]
    canvas:
        Color
            rgba: self.bgcolor
        Rectangle:
            pos: self.pos
            size: self.size

<Fruit>
    bgcolor: 0, 1, 0, 1

RelativeLayout
    canvas:
        Color
            rgba: 1, 0, 0, app.alpha
        Rectangle:
            pos: self.pos
            size: self.size
