# Generated by Django 2.1.1 on 2018-10-21 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_auto_20181021_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_related_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
